
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 
namespace TweakableEverything
{
	static class Version
	{
		public const int major = 0;
		public const int minor = 1;
		public const int patch = 24;
		public const int build = 3;
		public const string Number = "0.1.24.3";
		public const string Text = Number + " Unofficial";
	}
}
